### ISSUE TITLE
Cannot Compile under Microsoft Visual C# 2013

### ISSUE THREAD

**Issue by roycncn** [OmniKits/StringEx#2]
It will raise tones of errors. Like "; expected ".

I installed StringEx.cs in Nu-get, with "Install-Package StringEx.CS"

**Comment by Licshee** [comment]
hmmmm that sounds strange, I will check on it as soon as I get a vs2013 environment

**Comment by Licshee** [comment]
StringEx.CS is actually written in C# 6.0, guess that's why your compiler complains.
